import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // The .next/dev/types/validator.ts generated by Next.js 16 references
  // AppRouteHandlerRoutes which doesn't exist in routes.js at build time.
  // Our own TypeScript (checked via `tsc --noEmit`) passes with zero errors.
  env: {
    NEXT_PUBLIC_SUPABASE_URL:
      process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://ktqtpisunjguhclbdikg.supabase.co',
    NEXT_PUBLIC_SUPABASE_ANON_KEY:
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cXRwaXN1bmpndWhjbGJkaWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1OTU5NTAsImV4cCI6MjA5NjE3MTk1MH0.vV-mEew5CEAF1bdxeYa3EI0mWpIEsZyY-cPirV8Hk-k',
    NEXT_PUBLIC_APP_URL:
      process.env.NEXT_PUBLIC_APP_URL || 'https://localspo.my.id',
  },

  typescript: {
    ignoreBuildErrors: true,
  },

  // These packages use native binaries / dynamic requires incompatible with Turbopack bundling.
  // Mark them as external so Next.js loads them via Node's require() at runtime.
  serverExternalPackages: [
    '@distube/ytdl-core',
    'ytsr',
    'ytmusic-api',
  ],

  images: {
    remotePatterns: [
      // YouTube / YouTube Music thumbnails
      { protocol: 'https', hostname: '**.ytimg.com' },
      { protocol: 'https', hostname: '**.ggpht.com' },
      { protocol: 'https', hostname: '**.googleusercontent.com' },
      { protocol: 'https', hostname: 'lh3.googleusercontent.com' },
      { protocol: 'https', hostname: 'yt3.googleusercontent.com' },
      { protocol: 'https', hostname: 'i.ytimg.com' },
      // Supabase Storage
      { protocol: 'https', hostname: '**.supabase.co' },
      { protocol: 'https', hostname: '**.supabase.in' },
    ],
  },
};

export default nextConfig;
