import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // The .next/dev/types/validator.ts generated by Next.js 16 references
  // AppRouteHandlerRoutes which doesn't exist in routes.js at build time.
  // Our own TypeScript (checked via `tsc --noEmit`) passes with zero errors.
  typescript: {
    ignoreBuildErrors: true,
  },

  // These packages use native binaries / dynamic requires incompatible with Turbopack bundling.
  // Mark them as external so Next.js loads them via Node's require() at runtime.
  serverExternalPackages: [
    '@distube/ytdl-core',
    'ytdl-core',
    'yt-dlp-wrap',
    'ytsr',
    'ytmusic-api',
    'm3u8stream',
    'miniget',
  ],

  images: {
    remotePatterns: [
      // YouTube / YouTube Music thumbnails
      { protocol: 'https', hostname: '**.ytimg.com' },
      { protocol: 'https', hostname: '**.ggpht.com' },
      { protocol: 'https', hostname: '**.googleusercontent.com' },
      { protocol: 'https', hostname: 'lh3.googleusercontent.com' },
      { protocol: 'https', hostname: 'yt3.googleusercontent.com' },
      { protocol: 'https', hostname: 'i.ytimg.com' },
      // Supabase Storage
      { protocol: 'https', hostname: '**.supabase.co' },
      { protocol: 'https', hostname: '**.supabase.in' },
    ],
  },
};

export default nextConfig;
